name: extra_lints
version: 0.0.1
homepage:
description: Extra Lints provides some useful lints not included in Flutter Lints.
repository: https://github.com/LCostaN/extra_lints
issue_tracker: https://github.com/LCostaN/extra_lints/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: